Some fixs
DIXTRA/LandingYoyaku pull request #1
Opened 2021-08-05 16:39 UTC by Majo494

Se creo link logo. 
Se mejoro calidad logo
Se creo validacion de campos nombre y correo al enviar consulta
Se cambio imagen

2021-08-06 19:50 UTC, mauriguz requested changes

2021-08-06 19:50 UTC, mauriguz commented on app/assets/stylesheets/orders.scss
> +
```suggestion
```

2021-08-06 19:50 UTC, mauriguz commented on app/assets/stylesheets/orders.scss
> +.field_with_errors { display: inline }
```suggestion
.field_with_errors {
  display: inline
}

```

2021-08-06 19:50 UTC, mauriguz commented on app/assets/stylesheets/styles.css
> +.field_with_errors { display: none; }
```suggestion
.field_with_errors {
  display: none;
}
```

2021-08-06 19:50 UTC, mauriguz commented on app/assets/stylesheets/styles.css
> +}
```suggestion
}

```

2021-08-06 19:50 UTC, mauriguz commented on app/assets/stylesheets/styles.css
> +    height: calc(3.5rem + 2px);
I see that this same calc is being used in other places, does it make sense to move it to a variable? also, what it's supposed to accomplish?

2021-08-06 19:50 UTC, mauriguz commented on app/views/home/_form.html.erb
> +        <label for="inputName", class="<%=@order.errors[:name].any? ? 'error_explanation' : 'labelinput' %>"><%= form.label :name %></label>
any specific reason to wrap form.label in <label>? couldn't we just use form.label?

2021-08-06 19:50 UTC, mauriguz commented on app/views/home/index.html.erb
> +    <a href="#top">
I believe we don't need this new anchor, wrapping both title and image with the existing anchor should be enough

2021-08-06 19:50 UTC, mauriguz commented on app/views/home/index.html.erb
> + Basic features section
Is this intended?

2021-08-06 19:50 UTC, mauriguz commented on app/views/home/index.html.erb
> + App badge section
Idem

2021-08-06 19:50 UTC, mauriguz commented on app/views/home/index.html.erb
> + Footer
Idem

2021-08-06 19:50 UTC, mauriguz commented on config/environments/production.rb
> +  ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
isn't enough by adding it to config/environment?

2021-08-06 19:50 UTC, mauriguz commented on app/views/home/javascript.js.erb
> +    $('#modal-form').html('<%= j render "home/form" %>')
this is already in the html, why do we need it in both places?

2021-08-11 18:08 UTC, MathiasMoralesDixtra commented on app/assets/stylesheets/orders.scss
> +
Remove empty space

2021-08-11 18:08 UTC, MathiasMoralesDixtra commented on app/assets/stylesheets/orders.scss
> +.field_with_errors { display: inline }
Fix indentation and left one line at the left of the file

2021-08-11 18:08 UTC, MathiasMoralesDixtra commented on app/assets/stylesheets/styles.css
> +}
add empty line after this

2021-08-11 18:08 UTC, MathiasMoralesDixtra commented on app/assets/stylesheets/styles.css
> +.field_with_errors { display: none; }
```suggestion
.field_with_errors { 
    display: none;
 }
```

2021-08-11 18:08 UTC, MathiasMoralesDixtra commented on app/views/home/_form.html.erb
> +
delete empty line

2021-08-11 18:08 UTC, MathiasMoralesDixtra commented on config/database.yml
> -  host: ec2-54-147-93-73.compute-1.amazonaws.com
Probably we have to change this data, I don't know if this is in a singular commit or not, but in the case that it is a singular commit we have to delete this and would avoid changing this information. @mauriguz @Majo494 what do you think guys?

2021-08-16 15:41 UTC, mauriguz commented on app/views/home/_form.html.erb
> +
```suggestion
```

2021-08-16 15:48 UTC, mauriguz commented on config/database.yml
> -  host: ec2-54-147-93-73.compute-1.amazonaws.com
we'll revoke this info and move forward with other credentials, not a blocker for this pr

2021-08-16 18:14 UTC, mauriguz commented on app/assets/stylesheets/styles.css
> +    height: calc(3.5rem + 2px);
this file could use a full refactor, will ignore for now

2021-08-16 18:14 UTC, mauriguz commented on config/environments/production.rb
> +  ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
no need to fix in this PR

2021-08-16 18:15 UTC, mauriguz commented on app/views/home/javascript.js.erb
> +    $('#modal-form').html('<%= j render "home/form" %>')
yes it's needed

2021-08-16 18:15 UTC, mauriguz approved these changes

2021-08-16 19:55 UTC, MathiasMoralesDixtra approved these changes

2021-08-19 13:38 UTC, merged